name: skript-action

on: [push, pull_request]

jobs:
    runner:
        runs-on: ubuntu-latest
        steps:
            - name: ⬇️ Checkout
              uses: actions/checkout@v2

            - name: ✅ Run skript-action
              uses: Romitou/skript-action@1.0.0
